// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0G7RIEEeSO-mcS7vKmDVVwt0Y7GAR-HU',
    appId: '1:22958378691:web:bcf590ac71a8d736d91c76',
    messagingSenderId: '22958378691',
    projectId: 'ai-manager-49dff',
    authDomain: 'ai-manager-49dff.firebaseapp.com',
    storageBucket: 'ai-manager-49dff.appspot.com',
    measurementId: 'G-VT6GBE1CLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4WlZJzTs-eDi46MIn2cPUk6u_BGKmBSw',
    appId: '1:22958378691:android:972e11791e5d0572d91c76',
    messagingSenderId: '22958378691',
    projectId: 'ai-manager-49dff',
    storageBucket: 'ai-manager-49dff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB0_hMrj95rHsNFDizWnysfLAGR3tCokg',
    appId: '1:22958378691:ios:984f16699ba4e541d91c76',
    messagingSenderId: '22958378691',
    projectId: 'ai-manager-49dff',
    storageBucket: 'ai-manager-49dff.appspot.com',
    iosBundleId: 'com.unitsoft.aiManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB0_hMrj95rHsNFDizWnysfLAGR3tCokg',
    appId: '1:22958378691:ios:984f16699ba4e541d91c76',
    messagingSenderId: '22958378691',
    projectId: 'ai-manager-49dff',
    storageBucket: 'ai-manager-49dff.appspot.com',
    iosBundleId: 'com.unitsoft.aiManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0G7RIEEeSO-mcS7vKmDVVwt0Y7GAR-HU',
    appId: '1:22958378691:web:05c378af6a09cf1ad91c76',
    messagingSenderId: '22958378691',
    projectId: 'ai-manager-49dff',
    authDomain: 'ai-manager-49dff.firebaseapp.com',
    storageBucket: 'ai-manager-49dff.appspot.com',
    measurementId: 'G-S7GXSX4TPM',
  );
}
